Yuchu/create transponet
AequilibraE/qaequilibrae pull request #105
Opened 2018-08-26 20:39 UTC by ychtw

update create transponet

2018-08-26 22:10 UTC, pedrocamargo commented on AequilibraEMenu.py
> +        # pass
Just delete this line and the next.  Actually, it might be a good idea to delete all the #pass you have in there from previous PRs

2018-08-26 22:11 UTC, pedrocamargo commented on network/creates_transponet_dialog.py
> +                layer_fields = self.link_layer.fields()
Is it this, or 

layer_fields = self.link_layer.dataProvider().fields()

Did it work in tests for you?

2018-08-26 22:12 UTC, pedrocamargo commented on network/creates_transponet_dialog.py
>              pass
Maybe this pass should go too?

2018-08-26 22:13 UTC, pedrocamargo commented on network/creates_transponet_procedure.py
> +# from sqlite3 import dbapi2 as db
just remove it

2018-08-26 22:13 UTC, pedrocamargo commented on network/creates_transponet_procedure.py
> +        fields = layer.fields()
again, same thing with the dataProvider

2018-08-26 22:14 UTC, pedrocamargo requested changes
I made several small comments here.

It is pretty good work, but I think the suggested changes would be a good addition.

2018-08-26 22:14 UTC, pedrocamargo commented on network/forms/ui_transponet_construction.ui
> +   <string>AequilibraE - TranspoNet preparation</string>
Great catch!!

2018-09-06 23:10 UTC, pedrocamargo commented
Just waiting for these corrections to merge, @ychtw

2018-09-13 21:14 UTC, pedrocamargo commented on AequilibraEMenu.py
> +        # pass
I addressed it

2018-10-16 12:32 UTC, ychtw commented
I made those corrections, @pedrocamargo 
Thanks!

2018-10-17 11:18 UTC, pedrocamargo approved these changes

2018-10-17 11:18 UTC, merged