add processing provider v1
AequilibraE/qaequilibrae pull request #175
Opened 2021-05-10 17:45 UTC by Art-Ev

First version of processing provider (usable through processing toolbox and QGIS modeler)
Tested on QGIS 3.16 & 3.18 :
![image](https://user-images.githubusercontent.com/83211842/117701479-93ba4b00-b1c7-11eb-8360-a23b3ceb5597.png)
![image](https://user-images.githubusercontent.com/83211842/117701985-307ce880-b1c8-11eb-8562-34b6270f6263.png)

2021-05-10 18:09 UTC, Art-Ev reviewed
![image](https://user-images.githubusercontent.com/83211842/117704785-899a4b80-b1cb-11eb-8aa3-66e92040ea13.png)

2021-05-10 21:49 UTC, pedrocamargo commented on AequilibraEMenu.py
> +        try:
Broad try/except clauses are not a good workflow, as they tend to be quite broad and will fail Linting and we start using it (probably soon).  Is there a test to check if the provider exists and then remove it?

2021-05-10 21:50 UTC, pedrocamargo requested changes
Really nice work.  The only point to improve is that try/except and we can merge it into master!!

2021-05-10 22:45 UTC, jamiecook commented on processing_provider/Create_Nodes.py
> +        # Supprimer les géométries dupliquées
```suggestion
        # Remove duplicate geometries
```

2021-05-10 22:50 UTC, jamiecook approved these changes
Looks good to me, not sure what you want to do about mixing english/french in the comments and intermediate variable names. But overall legit - I think that the QGIS processing engine makes things more verbose than they need to be get-vertices, remove duplicates and filter for non-centroids would be 1-2 lines in pure geopandas for instance... but not much you can do about that if you want to use pure QGIS

2021-05-11 14:25 UTC, Art-Ev commented on AequilibraEMenu.py
> +        try:
Will take a look at this

2021-05-11 14:33 UTC, Art-Ev commented
> Looks good to me, not sure what you want to do about mixing english/french in the comments and intermediate variable names. But overall legit - I think that the QGIS processing engine makes things more verbose than they need to be get-vertices, remove duplicates and filter for non-centroids would be 1-2 lines in pure geopandas for instance... but not much you can do about that if you want to use pure QGIS

I'll be more careful not to mix French and English and I'll make a new pull request in full English. For the use of QGIS processes it's also easier for me for the moment but I'll try with geopandas (maybe some computing time to earn at the same time?)

2021-05-11 22:36 UTC, jamiecook commented
Sorry @Art-Ev - I didn't mean those comments directly for your immediate action, it's @pedrocamargo call on the EN/FR thing, and the geopandas comment was more of an observation on the differences between geopandas and QGIS.  I don't think it's possible to use geopandas in QGIS directly so your PR is the right way to do this. If you wanted to modify this PR to use english it would make it consistent with the rest of the codebase - but I'm sure that Pedro has left some Portugese in there somewhere :)

2021-05-13 10:39 UTC, pedrocamargo commented on AequilibraEMenu.py
> +        QgsApplication.processingRegistry().removeProvider(self.provider)
What happens if the provider does not exist?

2021-05-13 10:41 UTC, pedrocamargo commented on AequilibraEMenu.py
> +        QgsApplication.processingRegistry().removeProvider(self.provider)
Maybe something like this:

```suggestion
         if  self.provider in QgsApplication.processingRegistry().providers():
             QgsApplication.processingRegistry().removeProvider(self.provider)
```

2021-10-20 13:12 UTC, Art-Ev commented
Upload to AWS failed, is it possible to relaunch checks @pedrocamargo ?

2023-10-09 15:47 UTC, closed without merging