Adds test for Stacked Bandwidths
AequilibraE/qaequilibrae pull request #366
Opened 2024-09-23 13:14 UTC by r-akemii

In this PR we test the functions `DesireLinesDialog`, `DesireLinesProcedure`, `LoadColorRampSelector`, and `CreateBandwidthsDialog` from the GIS module, increasing the module coverage for visualization tools.

2024-09-23 13:19 UTC, r-akemii commented
@pedrocamargo with the addition of these new tests, we should reach 70% test coverage for QAequilibraE code. We're still missing tests for `SimpleTagDialog` and `LeastCommonDenominatorDialog` in the GIS module. I'm not sure what to do to test these functions, but I'll check with you later.

2024-10-02 13:00 UTC, pedrocamargo requested changes
Remote the use of desire lines. Add layer from test data (create some for that)

2024-10-02 17:21 UTC, r-akemii commented
@pedrocamargo I added a fixture in *conftest* to create an arbitrary line layer to test bandwidth creation, and the code piece that made the desirelines was tested separately in a new test file.

2024-10-03 00:41 UTC, pedrocamargo commented on qaequilibrae/modules/gis/desire_lines_procedure.py
> +        # print(self.results.link_loads)
remove this

2024-10-03 00:43 UTC, pedrocamargo commented on test/test_create_desirelines.py
> +        assert layer.featureCount() == 264
```suggestion
    target = 62 if is_delaunay else 264
    assert layer.featureCount() == target
```

2024-10-03 11:05 UTC, pedrocamargo approved these changes

2024-10-03 11:05 UTC, merged